### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by oresttokovenko** [sqlfluff/sqlfluff-online#389]
The website seems to be down

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by nolanbconaway** [comment]
Hi! Apologies for the delay-

Are you able to reproduce this error? The site is loading for me right now. Did you find the error after sending through a particular query?

**Comment by fey** [comment]
Got error too 
![image](https://github.com/user-attachments/assets/6173264f-d75f-45ce-ac78-a7cabc8884a2)
https://online.sqlfluff.com/fluffed?sql=H4sIAKiP-WYC_9PVVUhMT41PL8ovLSjm5Qp29XF1DuHlUgACDQgFAs6Owa4IHgiEe7j6oYqAQLIe0DAFO1sFQzNMSUc_F6gCG1sFI1OFEKARCuqGZrpGpuokGW5EyHATA6jhRma6JgZohrv6BLsqqJsYaCOJu_q5QDiaCo7B4ABJTixJTc8vqtSBiDv7h_qFaIAtQCjJL80r4eVyC_L3hShKLi0uyc9NLSoGqUjm5XIP8g8NUHCKVDDk5fIPcnENArOtebkAubffuXUBAAA%3D&dialect=PostgreSQL

## Steps to reproduce:

1. Go to online.sqlfluff.on
2. Put some code

```sql
-- age_groups
SELECT
    (
        CASE
            WHEN
                c.age >= 16
                AND c.age <= 25 THEN '16-25'
            WHEN
                c.age >= 26
                AND c.age <= 40 THEN '26-40'
            ELSE '40+'
        END
    ) AS age_category,
    COUNT(c.age) AS age_count
FROM
    customers AS c
GROUP BY 1
ORDER BY 1;
```

3. Error! `500 Internal Server Error`

**Comment by oresttokovenko** [comment]
@nolanbconaway The front end loads, but any query results in a 500 error

**Comment by nolanbconaway** [comment]
Yes I see now! On it. Thanks for raising the issue!

**Comment by fey** [comment]
I have start server on local, and got error

```bash
[2024-09-29 20:07:04,731] ERROR in app: Exception on /fluffed [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/api/simple.py", line 26, in get_simple_config
    dialect_selector(dialect)
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/core/dialects/__init__.py", line 98, in dialect_selector
    dialect = load_raw_dialect(s)
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/core/dialects/__init__.py", line 67, in load_raw_dialect
    raise KeyError("Unknown dialect")
KeyError: 'Unknown dialect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/src/app/routes.py", line 48, in fluff_results
    linted = lint(sql, dialect=dialect)
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/api/simple.py", line 87, in lint
    cfg = config or get_simple_config(
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/api/simple.py", line 30, in get_simple_config
    raise SQLFluffUserError(f"Error: Unknown dialect '{dialect}'")
sqlfluff.core.errors.SQLFluffUserError: Error: Unknown dialect 'PostgreSQL'
172.17.0.1 - - [2024-09-29 20:07:04] "GET /fluffed?sql=H4sIAGiz-WYC_8VW3W-bMBB_R-J_uLckW4JC2mYPaydlCW2ZEpiArtuTRYmbooWPgdMqUv_4GeyAnULSVprmPATM3c_38TvfDQYQbHKSRDjLUZBsYqIqrjE3ph5M7RvL6-6-onDZg0vHXtTyn1VFVQYDIEmK9CEiCfHXKIwD-lFVbk3vGnK8XlNBmLjQVRWgi2Gz52JhDUfpOtliTA8o5JgKfenXQl2s3YdZTlDsRxien6FDf_QPa2uf7_ZqXaZXmrrDLi2gRvUKi0UTuIEa--dHMsc_lJBJijOfhEmc84-Xc9t2uu7NoptrfzZ-TEKyhQ-QamkWBrhXKu1iUNrAj1AV07IMB77ZpgW5v2Y25WBbe0YUcbgA-lbIIHp8nsR0T9JPs2S5CUgJkZYQGt9i2qnwqipXjn3zHb7-Ah1sZ0Yx6OMJzAx3qipzc2F6oA93ufQfV2iJUz8jEY4JzyZFHI0_6eNxxQ0WhcmPq5YoMN95jCtnD_rAhdsd2Zm4Tp4wzbr_SDOzwv-GcPUj0zlGv1q-kYjC8fuM7BdecbP3fDrgRSNvi9WakgJMhm_3lye5FUuWlh2sLBSyLu4fZYAEcojWUsQbeSvcBFUVsr3GWqwh9215ZYUe8u8A-DEn6_ptusFkDrDCzDU51Q3Zl2-nBubRcNxeG44B-2BwXm41xltVqhtmREGmu5pd-luU3CPygNETxr_loi12qEDOd9FTSB5QvInuDlfy27qCwHbjp-dMpl7XdO2Zfcv5UWYTLX3ClLhN3AxB2XPMRdez0fR6UsS50upDh8p3WAPg7hYggmpr0xB7Rmvvegdt5bvuv1B21Ae9DyetrZeH52XAGJEF-kq0PUSZqpVRxq6yZJPm8sHCZTeduIbsGaV8wz0UaBQMvlyAPn75cWLNuMA57ZNn4FEI6Ojjweis8ybw0THw0yEHH40Hp8M9cGPuGtA5HX4U9g1rxl7YBUADElCqrpJsK4065QG1CJsC62u9GvgKiUCcJ4Ry13dhr8fJuy2Kkpg8yOFvrp0tXYMo6lQVG8Yrpi1ZOjNdz7Rob8o1aTClSmz8rE5_57j2ppHltWNXGZq_ik3y5moLAAA%3D&dialect=PostgreSQL HTTP/1.1" 500 991 0.003972
```

**Comment by nolanbconaway** [comment]
Nice find! fix incoming
